logging.level:
#  org.springframework.context: WARN
#  org.springframework.data: DEBUG
#  org.springframework.jdbc: DEBUG
#  example: DEBUG
  ROOT: DEBUG

spring:

  mvc:
    locale: en_US

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
